# Generated by Django 5.1.1 on 2024-10-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaRapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('tanggal', models.DateTimeField()),
                ('lokasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NotulenRapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_notulen', models.TextField()),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendarapat.agendarapat')),
            ],
        ),
        migrations.CreateModel(
            name='PesertaRapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pegawai', models.CharField(max_length=255)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta', to='agendarapat.agendarapat')),
            ],
        ),
    ]
